# Generated by Django 6.0.6 on 2026-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting for payment'), ('PREPARING', 'Making things ready'), ('SHIPPING', 'On the way'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceleds')], default='WAITING', max_length=50),
        ),
    ]
